### ISSUE TITLE
关于BERT参数冻结问题

### ISSUE THREAD

**Issue by menghuanlater** [thuiar/DeepAligned-Clustering#3]
感谢作者大大开源您的代码，我最近看了您的CDAC+和这篇模型，都发现您对BERT的前11层参数都采取了冻结的做法，我想问一下如果不冻结前11层参数，效果会是怎样的？还是说这样做是考虑到训练显存的问题，冻结前11层的参数可以在训练时设置更大的batch_size? 希望得到您的解答

**Comment by menghuanlater** [comment]
还有一个问题，我发现在DeepAligned论文中用的两个数据集，CDAC+普遍表现比BERT-KCL低，但为啥在CDAC+论文中却BERT-KCL高非常多，能解释下是什么原因吗？

**Comment by HanleiZhang** [comment]
> 感谢作者大大开源您的代码，我最近看了您的CDAC+和这篇模型，都发现您对BERT的前11层参数都采取了冻结的做法，我想问一下如果不冻结前11层参数，效果会是怎样的？还是说这样做是考虑到训练显存的问题，冻结前11层的参数可以在训练时设置更大的batch_size? 希望得到您的解答

您好，非常感谢您对我们工作的关注！这是一个很好的问题，关于freeze前11层，我们主要是出于**节约显存、提高运算效率**的目的，由下面的实验数据可以看出，当使用相同batch size，利用BERT全部12层进行微调是只利用最后一层进行微调的需要的GPU显存量的3倍多。为了公平比较，我们半监督方法的baseline也使用BERT作为backbone，因此总共需要的显存更多，模型十分笨重。
另外，我们还对比了只利用最后一层和全部层进行微调的模型效果，由下表的实验数据可以看出，使用全部层不一定比只利用最后一层进行微调效果好（前者在BANKING上较优，后者在CLINC上较优）。为了比较公平，其他使用BERT作为backbone的半监督聚类baseline也同样只用BERT最后一层进行微调，因此影响不大。

显存使用:
CLINC:  约3G (freeze 11 layers) -> 约10G (all 12 layers)
BANKING: 约4G (freeze 11 layers) -> 约12G (all 12 layers)

实验结果（5轮随机种子0-4平均）:
| Method   |       | CLINC |       |       |BANKING|       |   
|:--------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| Metric   |  NMI  |  ARI  |  ACC |  NMI  |  ARI  |  ACC  |
| use all 12 layers      | 92.21 | 73.44 | 81.01 | __80.92__ | __56.80__ | __68.30__ | 
| freeze 11 layers      | __93.89__| __79.75__ | __86.49__  | 79.56 | 53.64 | 64.90 |

**Comment by HanleiZhang** [comment]
> 还有一个问题，我发现在DeepAligned论文中用的两个数据集，CDAC+普遍表现比BERT-KCL低，但为啥在CDAC+论文中却BERT-KCL高非常多，能解释下是什么原因吗？

您好，是这样的，关于KCL [1]这篇论文原始是在CV数据集上做的，我们发现它的迁移聚类思想比较适合新意图发现任务，因此拿来用作baseline。KCL论文 （https://arxiv.org/pdf/1711.10125.pdf）中核心思路是先训练一个二分类判断数据对相似度的模型，然后用利用这个模型预测的数据对相似性作为先验知识，利用相对KL散度作为目标函数进行训练（原文公式1-5）。但是比较遗憾的是，我们发现这个方法 (KCL-BERT) 在文本意图数据集上并不是很work，CDAC+使用的三个数据集较简单，效果仍比较差。在本篇论文使用的两个数据集中，直接利用相对KL散度作为目标损失效果十分不理想，因此我们选择原文中4.3节提到的提升策略，在原损失的基础上增加了一个分类损失，效果有所提升，MCL-BERT[2]与KCL-BERT类似也采用了这个提升策略。

[1] Yen-Chang Hsu and Zhaoyang Lv and Zsolt Kira. 2018. Learning to Cluster in Order to Transfer Across Domains and Tasks. In Proceedings of ICLR 2018.
[2] Yen-Chang Hsu, Zhaoyang Lv, Joel Schlosser, Phillip Odom and Zsolt Kira. 2019. Multi-class classification without multi-class labels. In Proceedings of ICLR 2019.

**Comment by menghuanlater** [comment]
感谢您的解惑
